version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - ./nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password456
      - MYSQL_PASSWORD=password123
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=cs-nc

  app:
    image: nextcloud #:fpm
    restart: always
    links:
      - db
    ports:
      - 8081:80
    volumes:
      - ./nextcloud/nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=password123
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=cs-nc
      - MYSQL_HOST=db

  # web:
  #   image: nginx
  #   restart: always
  #   ports:
  #     - 8080:80
  #   links:
  #     - app
  #   volumes:
  #    - ./nextcloud/nginx/:/etc/nginx/
  #   volumes_from:  
  #     - app
