global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['cadvisor:8080']

  # - job_name: 'grafana'
  #   metrics_path: /metrics
  #   static_configs:
  #     - targets: ['grafana:3000']