services:
    rstudio:
        image: rocker/rstudio
        ports:
            - '8787:8787'
        environment:
            # username: rstudio
            PASSWORD: yourpassword
        volumes:
            - ./.rstudio_config:/home/rstudio/.config/rstudio
            - ./workspace:/home/rstudio/workspace
        stdin_open: true
        tty: true
